PUT http://localhost:8080/events/1
Content-Type: application/json
Authorization: 

{
    "name" : "updated test event",
    "description" : "A test event",
    "location" : "updated test location",
    "dateTime" : "2024-01-01T15:30:00.000Z" 
}